lane :bonjour do

scan(
	project: "EasyXMLParser.xcodeproj",
	code_coverage: true
)

xcov

end

lane :deploy do

	if git_branch() == "master"

		version = get_version_number()
		print version

		set_github_release(
			repository_name: "Asifadam93/EasyXMLParser",
			name: version,
			tag_name: "v#{version}",
			api_token: ENV["GITHUB_TOKEN"],
			description: changelog_from_git_commits(),
			commitish: "master"
		)
		pod_push()
	end

end
